services:
  - type: web
    name: rueda-de-proyectos
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
    healthCheckPath: /    # Render consultará la raíz para validar que responde 200
    healthCheckInterval: 5