services:
  - type: web
    name: rueda-de-proyectos
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
    healthCheckPath: /
    healthCheckInterval: 5
    buildCommand: ""
    startCommand: ""